config/routes.rb
ProblemOrNot::Application.routes.draw do

  resources :link_components

  devise_for :users

  match "/auth/:provider/callback" => 'authentications#create', :via => :get

  resources :authentications
  resources :problems do
    member do
      get 'resolve'
      post 'reopen'
    end

    collection do
      get 'search'
      post 'preview'
    end

    resources :comments
  end

  get 'problems_as_list' => 'problems#as_list'

  get 'problems/:id/version/:version' => 'problems#version', :as => 'problem_version'

  root :to => 'application#start'

end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :integer         not null, primary key
#  oppinion   :text
#  problem_id :integer
#  created_at :datetime        not null
#  updated_at :datetime        not null
#

class Comment < ActiveRecord::Base

  self.per_page = 5

  include Highlighter

  include PgSearch
  multisearchable :against => [:oppinion]

  belongs_to :problem, :touch => true
  # attr_accessible :oppinion, :user_id

  def oppinion_highlighted(search_term)
    highlight( oppinion, search_term || '')
  end

  def oppinion_markdown(search_term = '')
    BlueCloth.new(oppinion_highlighted(search_term)).to_html.html_safe
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  respond_to :html, :xml, :json, :js, :mobile

  layout 'small_header'

  before_filter :authorize_for_create, :only => :create
  load_and_authorize_resource :problem
  load_and_authorize_resource :through => :problem

  # POST /comments
  # POST /comments.json
  def create
    @problem = Problem.find params[:problem_id]
    @comment = @problem.comments.build params.require(:comment).permit(:oppinion, :problem_id)
    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment.problem }
        format.mobile { redirect_to problem_comments_path(@problem)}
        format.js
      else
        format.html { render action: "new" }
      end
    end
  end

  def index
    render :layout => !request.xhr?
  end

  # PUT /comments/1
  # PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to comments_url }
      format.json { head :no_content }
    end
  end

  # attr_accessible :oppinion, :user_id
private

  def comment_params
    params.require(:comment).permit(:oppinion, :problem_id)
  end

  def authorize_for_create
    params[:comment] = comment_params
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.haml
- if params[:action] =~ /search/
  %li
    %p
      = link_to comment.problem.title.first(45), problem_path(comment.problem, :query => params[:query])
      = image_tag 'chat.png', :title => "This problem has #{comment.problem.comments.count} comments" unless comment.problem.comments.empty?
- else
  %li.rounded.draggable
    = comment.oppinion_markdown params[:query]
    .timestamp= "Commented at: #{comment.created_at.relative_time}"

app/views/comments/_comment.html.slim
- if params[:action] =~ /search/
  li
    p
      = link_to comment.problem.title.first(45), problem_path(comment.problem, :query => params[:query])
      = image_tag 'chat.png', :title => "This problem has #{comment.problem.comments.count} comments" unless comment.problem.comments.empty?
- else
  li.rounded.draggable
    = comment.oppinion_markdown params[:query]
    .timestamp= "Commented at: #{distance_of_time_in_words_to_now(comment.created_at)}"

app/views/comments/_form.html.haml
= form_for([@problem, @comment], :remote => true) do |f|
  - if @comment.errors.any?
    #error_explanation
      %h2
        = "#{pluralize(@comment.errors.count, "error")} prohibited this comment from being saved:"

      %ul
        - @comment.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :oppinion, "Your oppinion"
    %br
    = f.text_area :oppinion, :cols => 75, :rows => 4
  = f.hidden_field :problem_id
  .actions
    = f.submit
    = link_to "Cancel", "#", :class => "cancel right"

app/views/comments/_form.html.slim
= form_for([@problem, @comment], :remote => true) do |f|
  - if @comment.errors.any?
    #error_explanation
      h2
        = "#{pluralize(@comment.errors.count, "error")} prohibited this comment from being saved:"

      ul
        - @comment.errors.full_messages.each do |msg|
          li= msg

  .field
    = f.label :oppinion, "Your oppinion"
    br
    = f.text_area :oppinion, :cols => 75, :rows => 4
  = f.hidden_field :problem_id
  .actions
    = f.submit
    = link_to "Cancel", "#", :class => "cancel right"

app/views/comments/create.js.erb
$('#new_comment').parent().remove()
$('.comments').prepend("<%=j render @comment %>")
$('#comment_operations').show()
problemOrNot.run_vital_functions()
$('.comments li:first').effect( "highlight", 'easeOutBounce', 4000)

app/views/comments/index.mobile.slim
div data-role='page' id='comments'
  div data-role='header'
    =link_to 'Back', problem_path(@comments.first.problem), {:'data-icon'=>"arrow-l"}
    h1= @comments.first.problem.title
    =link_to 'Express new oppinion', new_problem_comment_path(@comments.first.problem), :class => "ui-btn-right"
  div data-role='content'
    div data-role="collapsible-set"
      - @comments.each do |comment|
        div{'data-role'=>'collapsible', 'data-collapsed'=>'false'}
          h3= "#{distance_of_time_in_words_to_now(comment.created_at)}: #{comment.oppinion.first(20)}"
          p= comment.oppinion
  div data-role="footer"
    h6 or just a fragment of the past

app/views/comments/new.html.slim
h1 New comment

= render 'form'

= link_to 'Back', problems_path

app/views/comments/new.js.erb
$('.comments').prepend("<li class='rounded cancelable_remove'><%=j render :partial => 'form' %></li>");
$('#comment_operations').hide();
$('#comment_oppinion').focus();
problemOrNot.run_vital_functions();

app/views/comments/new.mobile.slim
div data-role='page' id='comments' data-add-back-btn='true'
  div data-role='header'
    h1 New oppinion
  div data-role='content'
    = form_for [@comment.problem, @comment] do |f|
      = f.label :oppinion, 'Your oppinion'
      = f.text_area :oppinion, :rows => 3
      = f.submit
  div data-role="footer"
    h6 or just a fragment of the past