config/routes.rb
ProblemOrNot::Application.routes.draw do

  resources :link_components

  devise_for :users

  match "/auth/:provider/callback" => 'authentications#create', :via => :get

  resources :authentications
  resources :problems do
    member do
      get 'resolve'
      post 'reopen'
    end

    collection do
      get 'search'
      post 'preview'
    end

    resources :comments
  end

  get 'problems_as_list' => 'problems#as_list'

  get 'problems/:id/version/:version' => 'problems#version', :as => 'problem_version'

  root :to => 'application#start'

end

app/models/problem.rb
# == Schema Information
#
# Table name: problems
#
#  id          :integer         not null, primary key
#  title       :string(255)
#  description :text
#  created_at  :datetime
#  updated_at  :datetime
#  user_id     :integer
#  state       :string(255)     default("existing")
#

class Problem < ActiveRecord::Base
  include PgSearch
  multisearchable :against => [:title, :description]

  belongs_to :user
  has_many :comments, -> { order(updated_at: :desc) }
  has_many :text_components
  # has_many :links

  has_paper_trail

  scope :existing, -> { where( :state => :existing)}
  scope :resolved, -> { where( :state => :resolved)}
  scope :sort_by_latest_update, -> {order(updated_at: :desc)}

  include Highlighter

  state_machine :state, :initial => :existing do

    event :resolve do
      transition [:existing] => :resolved
    end

    event :reopen do
      transition [:resolved] => :existing
    end

  end

  def description_markdown
    BlueCloth.new(description).to_html.html_safe
  end

  def title_highlighted(search_term)
    highlight( title, search_term)
  end

  def latest_comment
    comments.max_by { |comment| comment.updated_at }
  end

end

app/controllers/problems_controller.rb
class ProblemsController < ApplicationController
  before_filter :authorize_for_create_and_update, :only => [:create, :update]
  load_and_authorize_resource :except => :preview
  before_filter :authenticate_user!

  layout "small_header"

  def preview
    @preview = BlueCloth.new(params[:description]).to_html.html_safe
  end

  def search
    PgSearch.multisearch_options = {:using => { :tsearch => { :dictionary => "hungarian" } }, :ignoring => :accents}
    @result = PgSearch.multisearch(params[:query]).map{ |x| x.searchable }
    @result = @result.reject{|x| @result.include? x.problem rescue false}
    respond_to do |format|
      format.mobile { render :layout => !request.xhr? }
    end
  end

  def version
    v = Version.find(params[:version])
    @problem = v.reify
    authorize! :manage, @problem
    flash.now[:notice] = "This is a historical element created at: #{v.created_at}"
    render :show
  end

  def resolve
    p = Problem.find params[:id]
    authorize! :manage, p
    p.resolve
    redirect_to problems_path
  end

  def as_list
    @existing = @problems.existing.sort_by_latest_update
    @resolved = @problems.resolved.sort_by_latest_update
  end

  def index
    @existing = @problems.existing.sort_by_latest_update
    @resolved = @problems.resolved.sort_by_latest_update
  end

  # GET /problems/1
  # GET /problems/1.json
  def show
    request.headers
    respond_to do |format|
      format.html
      format.mobile{render :layout => !request.xhr?}
      format.js
    end
  end

  # GET /problems/new
  # GET /problems/new.json
  def new
    @problem.description = <<-HERE.strip_heredoc
    Your problem:
    -------------

    Items that **must** have:

    1. house
    3. table
    2. fridge

    Items to be _solved_:

    - It would be good to have a nice Ipad
    - and an Apple TV
    - an a Time capsule

    [Link to Apple](http://www.apple.com/)

    > Knowing others is intelligence; knowing yourself is true wisdom. Mastering others is strength; mastering yourself is true power. If you realize that you have enough, you are truly rich.

         This is a preformatted text1
         This is a preformatted text2
    HERE

    @preview = BlueCloth.new(@problem.description).to_html.html_safe

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @problem }
    end
  end

  def edit
    @preview = BlueCloth.new(@problem.description).to_html.html_safe
  end

  # POST /problems
  # POST /problems.json
  def create
    respond_to do |format|
      if @problem.save
        format.html { redirect_to @problem, notice: 'Problem was successfully created.' }
        format.json { render json: @problem, status: :created, location: @problem }
      else
        format.html { render action: "new" }
        format.json { render json: @problem.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /problems/1
  # PUT /problems/1.json
  def update
    respond_to do |format|
      if @problem.update_attributes(params[:problem])
        format.html { redirect_to @problem, notice: 'Problem was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @problem.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /problems/1
  # DELETE /problems/1.json
  def destroy
    @problem.destroy

    respond_to do |format|
      format.html { redirect_to problems_url }
      format.json { head :ok }
    end
  end

private

  def problem_params
    params.require(:problem).permit(:description, :title)
  end

  def authorize_for_create_and_update
    params[:problem] = problem_params
  end

end

app/helpers/problems_helper.rb
module ProblemsHelper
end

app/views/problems/_form.html.slim
= form_for(@problem) do |f|
  -if @problem.errors.any?
    #error_explanation
      h2
        = "#{pluralize(@problem.errors.count, "error")} prohibited this problem from being saved:"

      ul
      - @problem.errors.full_messages.each do |msg|
        li
          = msg

  .field
    = f.label :title
    br
    = f.text_field :title
  .field
    = f.label :description
    br
    = f.text_area :description, :cols => 80, :'data-preview-url' => preview_problems_url
  .actions
    = f.submit

- content_for :sidebar do
  h4 alt='Just copy and paste to it' title='Just copy and paste to it' How to Format
  ul.how-to-format
    li use returns for paragraphs
    li "- - -" for a horizontal line
    li _italic_ or **bold**
    li 
      span Title 1
      br
      span -------
    li 
      span - Unordered list item1
      br
      span - Green
      br
      span - Blue
    li
      span 1. Ordered list item1
      br
      span 2. Second item
      br
      span 3. Third item
    li links: [Link text](http://problem-or-not.herokuapp.com)
    li
      span > This is a blockquote
      br
      span > consectetuer adipiscing elit.
      br
      span > Vestibulum enim wisi.
      br
      span > Donec sit amet nisl.
    li 4 space folowed by preformated code on each line

preview
  = @preview if @preview.present?
 

app/views/problems/_problem.html.haml
%li
  %p
    = link_to problem.title.first(45), problem_path(problem, :query => params[:query])
    = image_tag 'chat.png', :title => "This problem has #{problem.comments.count} comments" unless problem.comments.empty?

app/views/problems/_problem.html.slim
li
  p
    = link_to problem.title.first(45), problem_path(problem, :query => params[:query])
    = image_tag 'chat.png', :title => "This problem has #{problem.comments.count} comments" unless problem.comments.empty?

app/views/problems/_quick_search.html.haml
.search
  = form_tag search_problems_path, :method => "get" do
    = text_field_tag 'query', '', :placeholder => 'search term'

app/views/problems/_quick_search.html.slim
.search
  = form_tag search_problems_path, :method => "get" do
    = text_field_tag 'query', '', :placeholder => 'search term'

app/views/problems/as_list.html.slim
.problems
  = render :partial => 'quick_search'

  h1 Listing problemss

  ul.sortable
    - @existing.each do |problem|
      li
        p= link_to problem.title.first(25), problem

  table.sortable
    tr
      th.wide Title
      th.small
      th.hidden.visible-on-hover-everywhere Timestamp
      th.hidden.visible-on-hover-everywhere.small Action

    - @existing.each do |problem|
      tr.mouse-stay.hover-table{:'data-hover' => 'visible-on-hover'}
        td.small-padding= link_to problem.title.first(25), problem
        td.small-padding= image_tag 'chat.png', :title => "This problem has #{problem.comments.count} comments" unless problem.comments.empty?
        td.hidden.visible-on-hover.unobtrusive.small-padding
          = distance_of_time_in_words_to_now(problem.updated_at) rescue ''
        td.hidden.visible-on-hover.small-padding
          = link_to problem, :method => :delete, data: {:confirm => 'Are you sure want to delete?'}, :class => 'simple-link', :title => 'delete permanently' do
            = image_tag 'trash.png', :size => "11x14"
          = link_to resolve_problem_path(problem), data: { :confirm => 'Are you sure want to resolve?'}, :class => 'simple-link', :title => 'resolve problem' do
            = image_tag 'resolve.png'
  br

  = link_to 'New Problem', new_problem_path

  - unless @resolved.empty?
    h2.past Fragments of the Past

    table
      tr
        th Title
        th
        th.hidden Action

      - @resolved.each do |problem|
        tr
          td.small-padding= link_to problem.title, problem
          td.small-padding= image_tag 'chat.png', :title => "This problem has #{problem.comments.count} comments" unless problem.comments.empty?

app/views/problems/edit.html.slim
h1 Editing problem

= render 'form'

= link_to 'Show', @problem 
| |
= link_to 'Cancel', problems_path

app/views/problems/index.html.slim
.problems
  = render :partial => 'quick_search'

  h1 Listing problemsss

  table
    tr
      th.wide Title
      th.small
      th.hidden.visible-on-hover-everywhere Timestamp
      th.hidden.visible-on-hover-everywhere.small Action

    - @existing.each do |problem|
      tr.mouse-stay.hover-table data-hover='visible-on-hover'
        td.small-padding= link_to problem.title.first(25), problem
        td.small-padding= image_tag 'chat.png', :title => "This problem has #{problem.comments.count} comments" unless problem.comments.empty?
        td.hidden.visible-on-hover.unobtrusive.small-padding
          = distance_of_time_in_words_to_now(problem.updated_at) rescue ''
        td.hidden.visible-on-hover.small-padding
          = link_to problem, :method => :delete, data: {:confirm => 'Are you sure want to delete?'}, :class => 'simple-link', :title => 'delete permanently' do
            = image_tag 'trash.png', :size => "11x14"
          = link_to resolve_problem_path(problem), data: { :confirm => 'Are you sure want to resolve?'}, :class => 'simple-link', :title => 'resolve problem' do
            = image_tag 'resolve.png'
  br

  = link_to 'New Problem', new_problem_path

  - unless @resolved.empty?
    h2.past Fragments of the Past

    table
      tr
        th Title
        th
        th.hidden Action

      - @resolved.each do |problem|
        tr
          td.small-padding= link_to problem.title, problem
          td.small-padding= image_tag 'chat.png', :title => "This problem has #{problem.comments.count} comments" unless problem.comments.empty?

app/views/problems/index.mobile.haml
div data-role='page' 'id'='problems'
  div data-role='header'
    h1 Problem or not
  div data-role='content'
    ul data-role>istview"
      - @existing.each do |problem|
        li.ui-li-has-count
          =link_to problem do
            =problem.title
            span.ui-li-count= problem.comments.count 
  div data-role="footer"
    h6 or just a fragment of the past

app/views/problems/preview.js.erb
$('preview').html('<%= j @preview %>');

app/views/problems/search.html.haml
= render :partial => 'quick_search'

=link_to 'Back to problems list', problems_path

%p= "Search result for:#{params[:query].split.map{|x| '\'' + x + '\''}.join(' ')}"

%ul
  = render @result

app/views/problems/search.html.slim
= render :partial => 'quick_search'

=link_to 'Back to problems list', problems_path

p= "Search result for:#{params[:query].split.map{|x| '\'' + x + '\''}.join(' ')}"

ul
  = render @result

app/views/problems/show.html.haml
.operations
  = link_to request.referrer =~ /search/ ? 'Back to search results' : 'Back to list', request.referrer =~ /search/ ? request.referrer : problems_path
  = link_to 'Edit', edit_problem_path(@problem)

.problem
  %p#notice= notice

  %p
    %b Title:
    = @problem.title

  %p.droppable
    %b Description:
    - @problem.text_components.each do |text_component|
      = text_component.description_markdown( params[:query])

  .left
    - unless @problem.resolved?
      = link_to 'Resolve', resolve_problem_path(@problem), data: { :confirm => 'Are you sure want to resolve?'}

  .right
    - if @problem.previous_version
      = link_to 'Back in Time', problem_version_path(@problem, @problem.previous_version.version.id)
    - unless @problem.live?
      = link_to 'Forward in Time', @problem.next_version ? problem_version_path(@problem, @problem.next_version.version.id) : @problem
  .clear

  %h3 Listing comments:

  #comment_operations
    = link_to 'Comment the problem', new_problem_comment_path( @problem), :remote => true

  - comments = @problem.comments.paginate(:page => params[:page])
  %ul.comments
    = render comments

  = will_paginate comments

app/views/problems/show.html.slim
.operations
  = link_to request.referrer =~ /search/ ? 'Back to search results' : 'Back to list', request.referrer =~ /search/ ? request.referrer : problems_path
  = link_to 'Edit', edit_problem_path(@problem)

.problem
  p#notice= notice

  p
    b Title:
    = @problem.title

  p.droppable
    b Description:
    = @problem.description_markdown

    - @problem.text_components.each do |text_component|
      = text_component.description_markdown( params[:query])

  .left
    - unless @problem.resolved?
      = link_to 'Resolve', resolve_problem_path(@problem), data: { :confirm => 'Are you sure want to resolve?'}

  .right
    - if @problem.previous_version
      = link_to 'Back in Time', problem_version_path(@problem, @problem.previous_version.version.id)
    - unless @problem.live?
      = link_to 'Forward in Time', @problem.next_version ? problem_version_path(@problem, @problem.next_version.version.id) : @problem
  .clear

  h3 Listing comments:

  #comment_operations
    = link_to 'Comment the problem', new_problem_comment_path( @problem), :remote => true

  - comments = @problem.comments.paginate(:page => params[:page])
  ul.comments
    = render comments

  = will_paginate comments