config/routes.rb
ProblemOrNot::Application.routes.draw do

  resources :link_components

  devise_for :users

  match "/auth/:provider/callback" => 'authentications#create', :via => :get

  resources :authentications
  resources :problems do
    member do
      get 'resolve'
      post 'reopen'
    end

    collection do
      get 'search'
      post 'preview'
    end

    resources :comments
  end

  get 'problems_as_list' => 'problems#as_list'

  get 'problems/:id/version/:version' => 'problems#version', :as => 'problem_version'

  root :to => 'application#start'

end

app/models/link_component.rb
class LinkComponent < ActiveRecord::Base
end

app/controllers/link_components_controller.rb
class LinkComponentsController < ApplicationController
  before_action :set_link_component, only: [:show, :edit, :update, :destroy]

  # GET /link_components
  def index
    @link_components = LinkComponent.all
  end

  # GET /link_components/1
  def show
  end

  # GET /link_components/new
  def new
    @link_component = LinkComponent.new
  end

  # GET /link_components/1/edit
  def edit
  end

  # POST /link_components
  def create
    @problem = Problem.find params[:problem_id]
    @link_component = LinkComponent.new(link_component_params)

    if @link_component.save
      redirect_to @link_component, notice: 'Link component was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /link_components/1
  def update
    if @link_component.update(link_component_params)
      redirect_to @link_component, notice: 'Link component was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /link_components/1
  def destroy
    @link_component.destroy
    redirect_to link_components_url, notice: 'Link component was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link_component
      @link_component = LinkComponent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def link_component_params
      params.require(:link_component).permit(:link)
    end
end

app/helpers/link_components_helper.rb
module LinkComponentsHelper
end

app/views/link_components/_form.html.erb
<%= form_for(@link_component) do |f| %>
  <% if @link_component.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@link_component.errors.count, "error") %> prohibited this link_component from being saved:</h2>

      <ul>
      <% @link_component.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :link %><br />
    <%= f.text_field :link %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/link_components/edit.html.erb
<h1>Editing link_component</h1>

<%= render 'form' %>

<%= link_to 'Show', @link_component %> |
<%= link_to 'Back', link_components_path %>

app/views/link_components/index.html.erb
<h1>Listing link_components</h1>

<table>
  <thead>
    <tr>
      <th>Link</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @link_components.each do |link_component| %>
    <tr>
      <td><%= link_component.link %></td>
      <td><%= link_to 'Show', link_component %></td>
      <td><%= link_to 'Edit', edit_link_component_path(link_component) %></td>
      <td><%= link_to 'Destroy', link_component, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br />

<%= link_to 'New Link component', new_link_component_path %>

app/views/link_components/new.html.erb
<h1>New link_component</h1>

<%= render 'form' %>

<%= link_to 'Back', link_components_path %>

app/views/link_components/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Link:</strong>
  <%= @link_component.link %>
</p>


<%= link_to 'Edit', edit_link_component_path(@link_component) %> |
<%= link_to 'Back', link_components_path %>